loader_name: combined

# path to the dataset files
dataset_path:

# save path for raw keypoints
raw_keypoints_save_dir: ""

# Other options
max_samples: null
splits_to_process:
  - train
  - validation
  - test
